<a href="https://colab.research.google.com/github/shrish-191/CELEBAL_TECH/blob/main/CelebalTech_ASS5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv('/content/titanic.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [31]:
cols = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols, axis=1)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [33]:
df = df.dropna()

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Pclass       712 non-null    int64  
 3   Sex          712 non-null    object 
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64  
 6   Parch        712 non-null    int64  
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB


In [35]:
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))

In [36]:
titanic_dummies = pd.concat(dummies, axis=1)

In [37]:
df = pd.concat((df,titanic_dummies), axis=1)

In [38]:
df = df.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Age          712 non-null    float64
 3   SibSp        712 non-null    int64  
 4   Parch        712 non-null    int64  
 5   Fare         712 non-null    float64
 6   1            712 non-null    bool   
 7   2            712 non-null    bool   
 8   3            712 non-null    bool   
 9   female       712 non-null    bool   
 10  male         712 non-null    bool   
 11  C            712 non-null    bool   
 12  Q            712 non-null    bool   
 13  S            712 non-null    bool   
dtypes: bool(8), float64(2), int64(4)
memory usage: 44.5 KB


In [40]:
df['Age'] = df['Age'].interpolate()


In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  712 non-null    int64  
 1   Survived     712 non-null    int64  
 2   Age          712 non-null    float64
 3   SibSp        712 non-null    int64  
 4   Parch        712 non-null    int64  
 5   Fare         712 non-null    float64
 6   1            712 non-null    bool   
 7   2            712 non-null    bool   
 8   3            712 non-null    bool   
 9   female       712 non-null    bool   
 10  male         712 non-null    bool   
 11  C            712 non-null    bool   
 12  Q            712 non-null    bool   
 13  S            712 non-null    bool   
dtypes: bool(8), float64(2), int64(4)
memory usage: 44.5 KB


In [42]:
X = df.values
y = df['Survived'].values

In [43]:
X = np.delete(X, 1, axis=1)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [46]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data
X_test_scaled = scaler.transform(X_test)

log_reg = LogisticRegression(max_iter=1000)
rf_clf = RandomForestClassifier()
svc_clf = SVC()



In [47]:
# Logistic Regression
log_reg.fit(X_train_scaled, y_train)

# Random Forest Classifier
rf_clf.fit(X_train, y_train)  # Random Forest does not need scaled data

# Support Vector Classifier
svc_clf.fit(X_train_scaled, y_train)



SVC()

In [48]:
# Logistic Regression
y_pred_log_reg = log_reg.predict(X_test_scaled)

# Random Forest Classifier
y_pred_rf_clf = rf_clf.predict(X_test)

# Support Vector Classifier
y_pred_svc_clf = svc_clf.predict(X_test_scaled)


In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Logistic Regression
print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_log_reg))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log_reg))
print("Classification Report:\n", classification_report(y_test, y_pred_log_reg))

# Random Forest Classifier
print("\nRandom Forest Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_rf_clf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf_clf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf_clf))

# Support Vector Classifier
print("\nSupport Vector Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_svc_clf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svc_clf))
print("Classification Report:\n", classification_report(y_test, y_pred_svc_clf))


Logistic Regression
Accuracy: 0.7710280373831776
Confusion Matrix:
 [[104  21]
 [ 28  61]]
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.83      0.81       125
           1       0.74      0.69      0.71        89

    accuracy                           0.77       214
   macro avg       0.77      0.76      0.76       214
weighted avg       0.77      0.77      0.77       214


Random Forest Classifier
Accuracy: 0.7897196261682243
Confusion Matrix:
 [[106  19]
 [ 26  63]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.85      0.82       125
           1       0.77      0.71      0.74        89

    accuracy                           0.79       214
   macro avg       0.79      0.78      0.78       214
weighted avg       0.79      0.79      0.79       214


Support Vector Classifier
Accuracy: 0.7757009345794392
Confusion Matrix:
 [[107  18]
 [ 30  59]]
Classificati